on: pull_request
jobs:
  static-check:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install dependencies
        run: pip3 install -r requirements.txt
      - name: Check lint
        run: make lint
      - name: Check mypy
        run: make mypy
