on: pull_request
jobs:
  static-check:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup python 3.6.x
        uses: actions/setup-python@v1
        with:
          python-version: 3.6.x
      - name: Check lint
        uses: make lint
      - name: Check mypy
        uses: make mypy
